fix(scripts): moved hardhat to be the first import
matter-labs/era-contracts pull request #195
Opened 2024-02-02 17:51 UTC by benceharomi

# What ❔
Moved the hardhat import to the top of the imports in scripts.

## Why ❔
When it was imported later, it caused some of the scripts to fail.

## Checklist
- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] ~~Tests for the changes have been added / updated.~~
- [ ] ~~Documentation comments have been added / updated.~~

2024-02-02 18:00 UTC, koloz193 approved these changes

2024-02-06 08:39 UTC, StanislavBreadless approved these changes

2024-02-06 08:40 UTC, StanislavBreadless requested changes

2024-02-06 08:40 UTC, StanislavBreadless commented on system-contracts/scripts/preprocess-bootloader.ts
> +    switch test_id
please remove this change so that hashes match again

2024-02-22 09:48 UTC, StanislavBreadless approved these changes

2024-02-23 13:56 UTC, merged