feat: BLS verification lib
matter-labs/era-contracts pull request #321
Opened 2024-04-08 02:11 UTC by moshababo

# What ❔

Adding BLS library for verification of aggregated signatures.

## Why ❔

To allow onchain verification of finalized blocks. 

## Notes

* Tests contain static test vector, generated by [era-consensus/node/libs/crypto](https://github.com/matter-labs/era-consensus/tree/main/node/libs/crypto).
* Integration code was not added. This will can done in a separate PR. 

TODOs:
- [ ] Add documentation
- [ ] Add more tests

2024-04-08 07:44 UTC, vladbochok commented on l1-contracts/test/unit_tests/BLS_test.spec.ts
> +    it("verifyAggregation: 2 signers", async function () {
We don't write tests in hardhat anymore. Please use Foundry instead

2024-04-08 07:49 UTC, vladbochok commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +    ) internal view returns (bool) {
What assumption do you have on the input data?

2024-04-08 07:49 UTC, vladbochok commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +    ) internal view returns (bool) {
Please document

2024-04-08 17:32 UTC, dnkolegov requested changes

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +library BLS {
Please document the curve name something like "This library implements the BLS signing scheme over the BN254 curve" or [that](https://github.com/getwax/bls-wallet/blob/ce7f958fb74b10e2b83bb886638b4ec0f64d9fac/contracts/contracts/lib/hubble-contracts/contracts/libs/BLS.sol#L10)

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +        if (!ecPairing(aggregated_sig, aggregated_pk2s, message_point)) {
Please document why we do not need a subgroup check for the signature. It will allow to decrease the number of FP in audit contests

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +    function verifyAggregation(
Please add the description of the function what are `pk1s`, `aggregated_pk2s`, etc.... and what the function does.

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +        require(pk1s.length >= 2, "BLS: number of pk1s must be at least 2");
The function can return false, true, and revert.
Would not be better to implement something like [that](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L13) to return concrete errors?

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +
Why do we not need to do a subgroup check for public keys?

2024-04-08 17:32 UTC, dnkolegov commented on l1-contracts/contracts/zksync/libraries/BLS.sol
> +        for (uint i = 2; i < pk1s.length; i++) {
- You should use explicit uint type here
- You can use pattern like [this one](https://github.com/matter-labs/era-contracts/blob/4aa7006153ad571643342dff22c16eaf4a70fdc1/l1-contracts/contracts/zksync/facets/Executor.sol#L305-L306) for loop

2024-05-09 12:45 UTC, brunoffranca commented
We decided to use ECDSA instead, so this PR is no longer needed.

2024-05-09 12:45 UTC, closed without merging